### ISSUE TITLE
vue-ckeditor Vue 1.x

### ISSUE THREAD

**Issue by pdroge84** [dangvanthanh/vue-ckeditor2#50]
Could anyone please tell me how to use this?

Can't seem to figure out how to get it working. I've got it in my package.json like this:
"vue-ckeditor": "git@github.com:dangvanthanh/vue-ckeditor2.git#1.0"
and it's being loaded successfully. But how to go on?

Thanks in advance.

**Comment by dangvanthanh** [comment]
No longer I'm not develop `vue-ckeditor2` for Vue 1.x. In `vue-ckeditor2` for use directives instead of component such as this version support Vue 2.x. If you want to use `vue-ckeditor2` you can clone source from `1.0` branch

Get `directives/ckeditor.js` file. From component you want to use I can define such as `ckeditor.vue`

```vue
<template>
	<div class="ckeditor">
        <textarea 
            class="ckeditor__textarea" 
            name="ckeditor" 
            id="ckeditor" 
            v-ckeditor="editorcontent" 
            v-bind:editorcontent="editorcontent" 
            debounce="100">
        </textarea>
	</div>
</template>

<script>
import Ckeditor from '../directives/ckeditor'

export default {
    directives: { Ckeditor },
    data () {
        return {
	    editorcontent: ''
        }
    }
}
</script>
```
